<%@ Page Title="" Language="VB" Debug="true" MasterPageFile="~/Sherut.master" MaintainScrollPositionOnPostback="true" AutoEventWireup="false" CodeFile="Forms.aspx.vb" Inherits="Forms" %>
<%@ Register assembly="System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI.WebControls" tagprefix="asp" %>
<%@ Register assembly="System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI" tagprefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server" >
    <div>
         <asp:ScriptManager ID="ScriptManager1" runat="server">
         </asp:ScriptManager>
     </div>
    <div>
    <table><tr valign="top"><td rowspan="2" width="250">
        
            <asp:XmlDataSource ID="XDGROUPS" runat="server" 
                DataFile="~/App_Data/lq.xml"></asp:XmlDataSource>
            <asp:TreeView ID="TVGROUPS" runat="server" DataSourceID="XDGROUPS" 
                RootNodeStyle-Font-Size="Large" RootNodeStyle-ForeColor="Blue" RootNodeStyle-Font-Bold="true"
                AutoGenerateDataBindings="false" ExpandDepth="0"> 
                <SelectedNodeStyle BackColor="#99CCFF" />
                <DataBindings>
                    <asp:TreeNodeBinding DataMember="Form" Textfield="txt" />
                      <asp:TreeNodeBinding DataMember="Title" TextField="txt" />
                      <asp:TreeNodeBinding DataMember="Group" TextField="txt" />
               </DataBindings>
                    <RootNodeStyle Font-Size="Large" Font-Bold="True" ForeColor="Blue"></RootNodeStyle>
            </asp:TreeView>
            <br />
         <asp:Label ID="LBLERR" runat="server" ForeColor="Red" 
            Text="הגדרת טופס לא חוקית" Visible="False" Width="400px"></asp:Label>
     
            <asp:Label ID="Label3" runat="server" Height="1px" Width="400px"></asp:Label>
            </td>
            <td valign="top" 
            style="border-style: solid; border-width: thin; border-color: #0000FF #0000FF #0000FF #66CCFF; font-weight:bold; background-color: #99CCFF;">
                <asp:label runat="server" ID="lblh1" Width="60">שם הלקוח:</asp:label><br />
                <asp:label runat="server" ID="lblh2">מס&#39; טופס:</asp:label><br />
                <asp:label runat="server" ID="lblh3">תאריך:</asp:label>
              </td>
            <td valign="top" style="border-style: solid; border-width: thin; border-color: #0000FF  #66CCFF #0000FF #0000FF; background-color: #99CCFF;">
                <asp:Label runat="server" Text="Label" ID="lblName"></asp:Label>
                <br />
                <asp:Label ID="lblNo" runat="server" Text="Label"></asp:Label><asp:Label runat="server" ID="lblstatus" 
                    Text="Label"></asp:Label>
                <br />
                <asp:textbox runat="server" ID="tbdate" Text="" Width="60" AutoPostBack="True" 
                    ToolTip="לשינוי התאריך הקש תאריך במבנה dd/mm/yy והקש enter" />
              </td>
              <td align="center">
                  <asp:HyperLink ID="HLBACK" runat="server" NavigateUrl="~/CustEventReport.aspx" ForeColor="#0066FF">חזרה</asp:HyperLink>
                  <asp:Button runat="server" Text="סגירה" Width="80px" ID="BTNCLS" onclientclick="return confirm('סגירת הטופס אינה מאפשרת לפתוח אותו שוב, האם לסגור?');"
                      onclick="BTNCLS_Click" /><br />
                   <asp:Button runat="server" Text="מחיקה" Width="80px" ID="BTNCNCL" 
                      onclientclick="return confirm('האם למחוק את הטופס?');" BackColor="#FFCC66" 
                      CausesValidation="False"  />
              </td>
            </tr>
            <tr>
            <td colspan="2" valign="top">
                <asp:RangeValidator ID="RangeValidator1" runat="server" 
                    ControlToValidate="tbdate" Display="Dynamic" ErrorMessage="תאריך לא חוקי" 
                    MaximumValue="2015-12-31" MinimumValue="2000-1-1" Type="Date"></asp:RangeValidator>
               </td>
               <td>
                  </td>
            </tr>
            </table>
  </div>
  <table>
      <tr>
            <td>
                <asp:Label ID="lblgrouphdr" runat="server" font-size="Large" Font-Bold="true" BackColor="Gray" Width="400px"></asp:Label>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="ראשון" />
            </td>
            <td>
                <asp:Button ID="Button2" runat="server" Text="הקודם" />
            </td>
            <td>
                <asp:Button ID="Button3" runat="server" Text="הבא" />
            </td>
            <td>
                <asp:Button ID="Button4" runat="server" Text="אחרון" />
            </td>
     </tr>
 </table>
 
  <asp:Panel runat="server" Height="570" Width="630" ScrollBars="Auto">
                           <asp:UpdatePanel runat="server" ID="up_q" >
                            <ContentTemplate>
     <div runat="server" id="divlvq" style="vertical-align:top">
        <asp:ListView ID="lv_q" runat="server">
            <LayoutTemplate>
                <table  cellpadding="4" border="2">
                    <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
                </table>
            </LayoutTemplate>
            <ItemTemplate>
                <tbody>
                    <tr>
                       <td style="background-color:Silver" >
                            <asp:Label ID="lblid_q" runat="server" Text='<%#Eval("id")%>' Width="10px" ></asp:Label>
                        </td>
                        <td style="background-color:Silver" >
                            <asp:Label ID="lbltxt_q" runat="server" Text='<%#Eval("txt")%>' Width="100px" ></asp:Label>
                        </td>
                        <td style='<%#Eval("style")%>'>
							<asp:Label runat="server" ID="lblSumGroup"  Visible='<%# Eval("sumGrp")="sum" %>'  Text='<%# Eval("fQ") & "|" & Eval("lQ") %>' OnPreRender="lblSumGroup_PreRender" />
							<asp:HiddenField runat="server" ID="hdnfQ" Value='<%# Eval("fQ") %>' />
   							<asp:HiddenField runat="server" ID="hdnlQ" Value='<%# Eval("lQ") %>' />
                             <asp:HiddenField ID="HDNANS_q" Value='<%#Eval("ans") %>' runat="server" />
                            <asp:HiddenField runat="server" ID="hdnid_q" value='<%#Eval("id")%>' />
                            <asp:HiddenField runat="server" ID="HDNAID_q" Value='<%#Eval("ansID") %>' />
                           <asp:RadioButtonList ID="rbla_q"  AutoPostBack="true" OnSelectedIndexChanged="rbla_SelectedIndexChanged" CausesValidation="true" OnPreRender="rbla_PreRender" CssClass="rbl" AppendDataBoundItems="true" runat="server" OnLoad="rbla_Load" RepeatDirection="Horizontal" DataTextField="txt" Font-Size="X-Small" RepeatLayout="Table" DataValueField="val" CellPadding="4" CellSpacing="2" width="450" >
                            </asp:RadioButtonList>
                             <asp:RangeValidator runat="server" ID="rvrbl" OnPreRender="rv_PreRender" ControlToValidate="rbla_q" SetFocusOnError="true" ErrorMessage="לא ניתן לשנות ערכים בטופס סגור" Display="Dynamic" Type="Integer" MaximumValue="-5" MinimumValue="-5" Enabled="false" />
                        </td>
                    </tr>
                </tbody>
           </ItemTemplate>
		</asp:ListView>
  </div>
<div runat="server" id="divlvp">
    <asp:ListView ID="lv_p" runat="server">
        <LayoutTemplate>
            <table>
                <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
            </table>
        </LayoutTemplate>
        <ItemTemplate>
            <tbody>
                <tr>
                    <td style='<%#Eval("style") %>'>
                        <asp:Label ID="lbltxt" runat="server" Text='<%#Eval("txt")%>' Width="600px" ></asp:Label>
                    </td>
                </tr>
            </tbody>
        </ItemTemplate>
    </asp:ListView>  
</div>
 <div runat="server" id="divlvs" style="vertical-align:top">
             <asp:ListView ID="lv_s" runat="server"  >
            <LayoutTemplate>
                <table cellpadding="4" border="2">
                <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
                </table>
           </LayoutTemplate>
           <ItemTemplate>
           <tbody>
           <div runat="server" id="divrow" >
           <tr>
           <td colspan="2" >
               <asp:Label ID="lblQ" runat="server" Text='<%#sF()%>' Width="540px" BackColor="Blue" ForeColor="Wheat" Font-Bold="true" Font-Size="Medium" OnPreRender="lblQ_PreRender"></asp:Label>
           </td>
           </tr>
           </div>
            <tr>
                   <td style="background-color:Silver">
                   <asp:HiddenField runat="server" ID="hdng_s" Value='<%#Eval("parent") %>' />
                   <asp:HiddenField runat="server" ID="HDNAID_s" Value='<%#Eval("ansID") %>' />
                   <asp:HiddenField ID="HDNANS_S" Value='<%#Eval("ans") %>' runat="server" />
                   <asp:HiddenField runat="server" ID="hdnid_S" value='<%#Eval("id")%>' />
                   <asp:Label ID="lbltxt_S" runat="server" Text='<%#Eval("txt")%>' Width="100px" ></asp:Label>
                </td>
                <td>
                    <asp:TextBox ID="TBDET_S" AutoPostBack="true"  OnTextChanged="tb_OnTextChanged" runat="server" TextMode="MultiLine" Width="450px" Visible='<%#Eval("tb") = "yes" %>' Text='<%#Eval("textdet") %>'></asp:TextBox>
                    <asp:RadioButtonList ID="rbla_S"  AutoPostBack="true" OnSelectedIndexChanged="rbla_SelectedIndexChanged" CausesValidation="true" OnPreRender="rbla_PreRender" CssClass="rbl" AppendDataBoundItems="true" runat="server" OnLoad="rbla_Load" RepeatDirection="Horizontal" DataTextField="txt" Font-Size="X-Small" RepeatLayout="Table" DataValueField="val" CellPadding="4" CellSpacing="2" width="450" >
                    </asp:RadioButtonList>
                              <asp:RangeValidator runat="server" ID="rvrbl" OnPreRender="rv_PreRender" ControlToValidate="rbla_S" SetFocusOnError="true" ErrorMessage="לא ניתן לשנות ערכים בטופס סגור" Display="Dynamic" Type="Integer" MaximumValue="-5" MinimumValue="-5" Enabled="false" />
               </td>
            </tr>
            </tbody>
           </ItemTemplate>
            </asp:ListView>  
  </div>
  <div runat="server" id="divrlq" style="vertical-align:top">
  <asp:listview runat="server" ID="lvr_r">
    <LayoutTemplate>
        <table  border="1" cellpadding="3">
                   <thead style="background-color:Silver" align="center">
                <tr>
                    <td colspan="3" align="center" style="font-weight:bold">תוצאות</td>
                </tr>
                <tr>
                    <td align="right">
                        <asp:label runat="server" ID="lblcri" OnPreRender="lblcri_PreRender" text="טווח רמת המשכל" Width="120" />
                    </td>
                    <td  colspan="2"  align="center" style="font-weight:bold">
                        <asp:RadioButtonList ID="rblcr" runat="server" ToolTip="בחרו את העמודה הרלוונטית בהתאם לטווח רמת המשכל" AutoPostBack="true" RepeatDirection="Horizontal" OnPreRender="rblcr_PreRender" OnLoad="rblcr_Load" OnSelectedIndexChanged="rblcr_SelectedIndexChanged" />
                        <asp:Label ID="lblcr" OnPreRender="lblcr_PreRender" runat="server" />
                    </td>
                </tr>
                <tr>
                    <td style="width:80px">סולם</td>
                    <td style="width:80px">מדרג</td>
<!--                    <td style="width:80px">מדרג 2</td>
                    <td style="width:80px">ממוצע מדרגים או דיווח עצמי</td>/!-->
                    <td style="width:80px">אחוזון</td>
                </tr>
            </thead>
            <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
           <tfoot style="background-color:Silver">
        <tr>
            <td>ציון סופי</td>
            <td>
                <asp:Label runat="server" ID="lblsdrg1" Text="" OnPreRender="lblsdrg1_PreRender"></asp:Label>
            </td>
            <!-- <td>
                <asp:Label runat="server" ID="lblsdrg2" Text="" ></asp:Label>
            </td>
            <td>
                <asp:Label runat="server" ID="lblsAVG" Text="" ></asp:Label>
            </td>  /!-->
             <td>
                <asp:Label runat="server" ID="lblsprc" Text="" OnPreRender="lblsprc_PreRender"></asp:Label>
            </td>
      </tr>
    </tfoot>
</table>
 </LayoutTemplate>
 <itemtemplate>
    <tbody>
        <tr>
            <td>
                <asp:Label runat="server" ID="lblgrp" Text='<%#Eval("grp") %>' Width="180" ></asp:Label>
            </td>
            <td>
                <asp:Label runat="server" ID="lbldrg1" Text='<%#val("sumg") %>' ></asp:Label>
            </td>
  <!--          <td>
                <asp:Label runat="server" ID="lbldrg2" Text="" ></asp:Label>
            </td>
            <td>
                <asp:Label runat="server" ID="lblavg" Text="" ></asp:Label>
            </td> /!-->
            <td>
                <asp:Label runat="server" ID="lblprc" Text='<%#Eval("perc") %>' ></asp:Label>
            </td> 
        </tr>
    </tbody>
 </ItemTemplate>
  </asp:listview>
  </div>
  <div runat="server" id="divrsis">
     <asp:ListView ID="lvsis" runat="server"  >
        <LayoutTemplate>
          <table border="1" cellpadding="3">
            <thead style="background-color:Silver">
                <tr>
                    <td colspan="4" align="center" style="font-weight:bold">מדרוג צרכי התמיכה</td>
                </tr>
                <tr>
                    <td>פעילויות</td>
                    <td>ניקוד שורה כללי</td>
                    <td>ניקוד סטנדרטי</td>
                    <td>אחוזים</td>
                </tr>
            </thead>
            <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
           <tfoot style="background-color:Silver">
        <tr>
            <td colspan="2">סיכום הניקוד הסטנדרטי</td>
            <td>
                <asp:Label runat="server" ID="lblsums" OnPreRender="lblsums_PreRender" Text="" ></asp:Label>
            </td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">אינדקס צרכי תמיכות</td>
            <td>
                <asp:Label runat="server" ID="lblindex" Text="" OnPreRender="lblindex_PreRender" ></asp:Label>
            </td>
            <td></td>
        </tr>
       <tr>
            <td colspan="2"></td>
            <td></td>
            <td>
                <asp:Label runat="server" ID="lblspercent" Text="" ></asp:Label>
            </td>
        </tr>
    </tfoot>
          </table>
      </LayoutTemplate>
      <ItemTemplate>
          <tbody>
                <tr>
                    <td>
                        <asp:Label runat="server" ID="lblGroup" Text='<%#Eval("grp")  %>' ></asp:Label>
                    </td>
                    <td>
                        <asp:Label runat="server" ID="lblsumg" Text='<%#Eval("sumg") %>' ></asp:Label>
                    </td>
                    <td>
                        <asp:Label runat="server" ID="lblstandard" Text='<%#val("stan") %>' ></asp:Label>
                    </td>
                    <td>
                        <asp:Label runat="server" ID="lblpercentage" Text='<%#Eval("perc") %>' ></asp:Label>
                    </td>
                </tr>
           </tbody>
        </ItemTemplate>
    </asp:ListView>
  
    <br/>
   <div>
   <table border="1">
        <thead style="background-color:Silver">
            <tr>
                <td colspan="9" align="center" style="font-weight:bold">פרופיל צרכי תמיכה</td>
            </tr>
            <tr>
                <td width="60px" align="center">אחוזון</td>
                <td width="60px" align="center">אינדקס צרכי תמיכות</td>
                <td width="60px" align="center">פעולות חברתיות</td>
                <td width="60px" align="center">פעולות בריאות ובטיחות</td>
                <td width="60px" align="center">פעולות תעסוקה</td>
                <td width="60px" align="center">פעולות למידה לאורך החיים</td>
                <td width="60px" align="center">פעולות חיים בקהילה</td>
                <td width="60px" align="center">פעולות בבית</td>
                <td width="60px" align="center">אחוזון</td>
            </tr>
        </thead>
        <tbody align="center">
<tr>
<td><asp:Label runat="server" ID="lblb1_00_00_" text="99" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_07_132" text=">131" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_06_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_05_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_04_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_03_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_02_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_01_017" text="17-20" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_00_08_" text="99" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_01_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_07_124" text="124-131" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_06_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_05_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_04_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_03_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_02_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_01_015" text="15-16" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_01_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_02_00_" text="90" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_07_120" text="120-123" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_06_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_05_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_04_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_03_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_02_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_01_014" text="14" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_02_08_" text="90" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_03_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_07_116" text="116-119" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_06_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_05_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_04_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_03_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_02_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_01_013" text="13" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_03_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_04_00_" text="80" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_07_113" text="113-115" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_06_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_05_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_04_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_03_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_02_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_01_013" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_04_08_" text="80" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_05_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_07_110" text="110-112" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_06_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_05_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_04_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_03_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_02_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_01_012" text="12" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_05_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_06_00_" text="70" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_07_108" text="108-109" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_06_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_05_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_04_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_03_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_02_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_01_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_06_08_" text="70" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_07_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_07_106" text="106-107" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_06_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_05_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_04_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_03_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_02_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_01_012" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_07_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_08_00_" text="60" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_07_105" text="105" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_06_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_05_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_04_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_03_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_02_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_01_011" text="11" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_08_08_" text="60" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_09_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_07_102" text="102-104" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_06_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_05_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_04_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_03_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_02_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_01_011" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_09_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_10_00_" text="50" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_07_100" text="100-101" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_06_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_05_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_04_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_03_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_02_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_01_010" text="10" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_10_08_" text="50" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_11_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_07_098" text="98-99" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_06_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_05_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_04_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_03_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_02_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_01_010" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_11_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_12_00_" text="40" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_07_097" text="97" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_06_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_05_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_04_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_03_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_02_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_01_009" text="9" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_12_08_" text="40" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_13_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_07_094" text="94-96" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_06_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_05_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_04_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_03_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_02_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_01_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_13_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_14_00_" text="30" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_07_092" text="92-93" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_06_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_05_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_04_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_03_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_02_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_01_009" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_14_08_" text="30" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_15_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_07_090" text="90-91" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_06_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_05_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_04_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_03_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_02_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_01_008" text="8" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_15_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_16_00_" text="20" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_07_088" text="88-89" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_06_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_05_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_04_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_03_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_02_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_01_008" text="_" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_16_08_" text="20" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_17_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_07_085" text="85-87" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_06_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_05_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_04_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_03_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_02_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_01_007" text="7" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_17_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_18_00_" text="10" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_07_082" text="82-84" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_06_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_05_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_04_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_03_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_02_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_01_006" text="6" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_18_08_" text="10" Width="60px" /></td>
</tr>
<tr style="background-color:#DDDDDD">
<td><asp:Label runat="server" ID="lblb1_19_00_" text="" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_07_075" text="75-81" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_06_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_05_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_04_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_03_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_02_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_01_005" text="5" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_19_08_" text="" Width="60px" /></td>
</tr>
<tr>
<td><asp:Label runat="server" ID="lblb1_20_00_" text="1" Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_07_001" text="<74" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_06_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_05_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_04_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_03_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_02_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_01_001" text="1-4" OnPreRender="lblb1_PreRender"  Width="60px" /></td>
<td><asp:Label runat="server" ID="lblb1_20_08_" text="1" Width="60px" /></td>
</tr>
</tbody>
</table>
</div>
<div>
 <br />
    <asp:ListView ID="lvsis2" runat="server">
        <LayoutTemplate>
            <table border="1" cellpadding="3">
                <thead style="background-color:Silver">
                    <tr>
                        <td align="center" colspan="2" style="font-weight:bold">
                            שיקולי תמיכה המתבססים על ציוני הגנה וסינגור</td>
                    </tr>
                    <tr>
                        <td>
                            פעילויות (4 הציונים הגבוהים ביותר)</td>
                        <td>
                            ציון שורה</td>
                    </tr>
                </thead>
                <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
            </table>
        </LayoutTemplate>
        <ItemTemplate>
            <tbody>
                <tr>
                    <td>
                        <asp:Label ID="lblsgr" runat="server" Text='<%#Eval("sgrpnam") %>' />
                    </td>
                    <td>
                        <asp:Label ID="lblsum" runat="server" Text='<%#Eval("sumg") %>' />
                    </td>
                </tr>
            </tbody>
        </ItemTemplate>
    </asp:ListView>
</div>
<div>
<br />
    <table border="1" cellpadding="3">
        <thead style="background-color:Silver">
            <tr>
                <td align="center" colspan="2" style="font-weight:bold">
                    שיקולי תמיכה המתבססים על צרכים רפואיים והתנהגותיים חריגים</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td align="right" colspan="2" style="font-weight:bold;background-color:silver">א. רפואי</td>
            </tr>
            <tr>
                <td>מספר הנקודות הכללי</td>
                <td>
                    <asp:Label ID="lblmed1" runat="server" Text="" />
                </td>
            </tr>
            <tr>
                <td>האם המספר גדול מ 5?</td>
                <td>
                    <asp:Label ID="lblmed2" runat="server" Text="" />
                </td>
            </tr>
            <tr>
                <td>האם סומנו לפחות שתי תמיכות רפואיות?</td>
                <td>
                    <asp:Label ID="lblmed3" runat="server" Text="" />
                </td>
            </tr>
            <tr>
                <td align="right" colspan="2" style="font-weight:bold;background-color:silver">ב. התנהגותי</td>
            </tr>
           <tr>
                <td>מספר הנקודות הכללי</td>
                <td>
                    <asp:Label ID="lblbeh1" runat="server" Text="" />
                </td>
            </tr>
            <tr>
                <td>האם המספר גדול מ 5?</td>
                <td>
                    <asp:Label ID="lblbeh2" runat="server" Text="" />
                </td>
            </tr>
            <tr>
                <td>האם סומנו לפחות שתי תמיכות התנהגותיות?</td>
                <td>
                    <asp:Label ID="lblbeh3" runat="server" Text="" />
                </td>
            </tr>
        </tbody>
        </table>
</div>
</div>
<div runat="server" id="diveduResults" visible="false">
	<asp:ListView runat="server" ID="lveduResults">
		<LayoutTemplate>
			<table border="1">
				<thead style="background-color:Silver;font-weight:bold;">
					<tr>
						<td>תחום</td>
						<td>רמת תמיכה</td>
					</tr>
				</thead>
				<tr ID="itemPlaceholder" runat="server">
				</tr>
				<tr>
				</tr>
			</table>
		</LayoutTemplate>
		<ItemTemplate>
			<tr>
				<td><asp:Label runat="server" ID="lblName" Text='<%# Eval("Name")%>' /></td>
				<td><asp:Label runat="server" ID="lblRT" Text='<%# Eval("RT", "{0:0.00}")%>' /></td>
			</tr>
		</ItemTemplate>
	</asp:ListView>
	<asp:Chart runat="server" ID="chrtG" Width="600px" Height="380px">
	</asp:Chart>
</div>
 
                     </ContentTemplate>
                    </asp:UpdatePanel>
  </asp:Panel>
 
  <div>
    <table>
        <tr>
            <td>
                <asp:Label ID="lblspace" runat="server" font-size="Large" Font-Bold="true" Width="400px"></asp:Label>
            </td>
            <td>
                <asp:Button ID="Button1A" runat="server" Text="ראשון" />
            </td>
            <td>
                <asp:Button ID="Button2A" runat="server" Text="הקודם" />
            </td>
            <td>
                <asp:Button ID="Button3A" runat="server" Text="הבא" />
            </td>
            <td>
                <asp:Button ID="Button4A" runat="server" Text="אחרון" Width="42px" />
            </td>
        </tr>
    </table>
  </div>
</asp:Content>

