<%@ Page Title="" Language="VB" Debug="true" MasterPageFile="~/Surveys.master" AutoEventWireup="false" CodeFile="Surveys.aspx.vb" Inherits="Surveys"  enableViewStateMac="false" validateRequest="false" enableEventValidation="false" viewStateEncryptionMode ="Never"  %>
<%@ Register assembly="System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI.WebControls" tagprefix="asp" %>
<%@ Register assembly="System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI" tagprefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server" >
    <div>				
 
         <asp:HyperLink ID="HyperLink1" runat="server" Font-Size="XX-Large" 
             Height="200px" NavigateUrl="http://www.be-online.org/surveyentry.aspx?s=8" 
             Width="500px" BackColor=Pink>הקלק כאן לעבור למערכת הסקרים</asp:HyperLink>
 
         <asp:ScriptManager ID="ScriptManager1" runat="server">
         </asp:ScriptManager>
  <script language="javascript" type="text/javascript"> 

//             function postBackByObject() {
//                 var o = window.event.srcElement;
//                 if (o.tagName == "INPUT" && o.type == "checkbox") {
//                     __doPostBack("", "");
//                 }
//             }
//             //  var whichrow = false
//       //                if (x.style.backgroundColor != 'transparent') 

             function thisrow(x) {
//             var radio = x
//             alert(radio.length);
//            for (var j = 0; j < 5; j++) 
//                {
//                alert(j);
//                    if (x[j].checked)
//                        {
                            x.style.backgroundColor = 'transparent';
 //                       }
//                }
    }
</script>


     </div>
    <div>
    <table><tr valign="top"><td rowspan="2" >
    <asp:XmlDataSource DataFile="~/App_Data/Frames.xml" ID="xFrames" runat="server"  />
        
            <asp:XmlDataSource ID="XDGROUPS" runat="server" 
                DataFile="~/App_Data/lq.xml"></asp:XmlDataSource>
            <asp:TreeView ID="TVGROUPS" runat="server" DataSourceID="XDGROUPS" 
                RootNodeStyle-Font-Size="Large" RootNodeStyle-ForeColor="Blue" RootNodeStyle-Font-Bold="true"
                AutoGenerateDataBindings="false" ExpandDepth="0">
                <SelectedNodeStyle BackColor="#99CCFF" />
                <DataBindings>
                    <asp:TreeNodeBinding DataMember="Form" Textfield="txt" />
                      <asp:TreeNodeBinding DataMember="Title" TextField="txt" />
                      <asp:TreeNodeBinding DataMember="Group" TextField="txt" />
               </DataBindings>
                    <RootNodeStyle Font-Size="Large" Font-Bold="True" ForeColor="Blue"></RootNodeStyle>
            	<NodeStyle Font-Underline="True" />
            </asp:TreeView>
            <asp:Label ID="lblNF" runat="server" Font-Size="Medium" ForeColor="Red" Width="100%" Visible="false"></asp:Label>
            <br />
         <asp:Label ID="LBLERR" runat="server" ForeColor="Red" 
            Text="הגדרת טופס לא חוקית" Visible="False" Width="400px"></asp:Label>
            <div runat="server" id="divSelectFrame" visible="false">
				<table border="1">
					<tr>
						<td>
						
							<asp:DropDownList ID="ddlservice" runat="server" AppendDataBoundItems="True" 
								AutoPostBack="True" DataSourceID="dsservice" DataTextField="ServiceName" 
								DataValueField="ServiceID">
								<asp:ListItem Value="">&lt;בחר שירות&gt;</asp:ListItem>
							</asp:DropDownList>
						
						</td>
						<td>
							<asp:DropDownList ID="ddlframe" runat="server" AppendDataBoundItems="True" EnableViewState="False"
								DataSourceID="dsframe" DataTextField="FrameName" DataValueField="FrameID" AutoPostBack="True">
								<asp:ListItem Value="">&lt;בחר מסגרת&gt;</asp:ListItem>
							</asp:DropDownList>
						</td>
						<td>
						מסגרת
						</td>
						<td>
							<asp:Label runat="server" ID="lblframe" />
						</td>
						<td>
						טופס
						</td>
						<td>
							<asp:label runat="server" ID="lblformid" />
 						</td>
					</tr>
				</table>
				<asp:SqlDataSource ID="dsframe" runat="server" 
					ConnectionString="<%$ ConnectionStrings:bebook10 %>" 
					SelectCommand="SELECT [FrameName], [FrameID] FROM [FrameList] WHERE ([ServiceID] = @ServiceID) ORDER BY [FrameName]">
					<SelectParameters>
						<asp:ControlParameter ControlID="ddlservice" Name="ServiceID" 
							PropertyName="SelectedValue" Type="Int32" />
					</SelectParameters>
				</asp:SqlDataSource>
				<asp:SqlDataSource ID="dsservice" runat="server" 
					ConnectionString="<%$ ConnectionStrings:bebook10 %>" 
					SelectCommand="SELECT [ServiceName], [ServiceID] FROM [ServiceList] ORDER BY [ServiceID]">
				</asp:SqlDataSource>


			</div>
			

     
                  <asp:Button runat="server" Text="שליחה למערכת"  ID="BTNCLS" onclientclick="return confirm('?לא ניתן יהיה לשנות את התשובות, האם לשלוח למערכת');" Visible="false"
                      onclick="BTNCLS_Click" />
     
            <asp:Label ID="Label3" runat="server" Height="1px" Width="100%"></asp:Label>
            </td>
            <td><table visible="false"><tr>
				<td valign="top" 
				style="border-style: solid; border-width: thin; border-color: #0000FF #0000FF #0000FF #66CCFF; font-weight:bold; background-color: #99CCFF;" visible="false">
					<div runat="server" visible="false">
						<asp:label runat="server" ID="lblh1" Width="60">שם הלקוח:</asp:label><br />
						<asp:label runat="server" ID="lblh2">מס&#39; טופס:</asp:label><br />
						<asp:label runat="server" ID="lblh3">תאריך:</asp:label>
					</div>
				  </td>
				<td valign="top" style="border-style: solid; border-width: thin; border-color: #0000FF  #66CCFF #0000FF #0000FF; background-color: #99CCFF;" visible="false">
   					<div runat="server" visible="false">

						<asp:Label runat="server" Text="Label" ID="lblName"></asp:Label>
						<br />
						<asp:Label ID="lblNo" runat="server" Text="Label"></asp:Label><asp:Label runat="server" ID="lblstatus" 
							Text="Label"></asp:Label>
						<br />
						<asp:textbox runat="server" ID="tbdate" Text="" Width="60" AutoPostBack="True" 
							ToolTip="לשינוי התאריך הקש תאריך במבנה dd/mm/yy והקש enter" />
					</div>
				 </td>
             </tr></table>
			</td>
              <td align="center">
                  <asp:HyperLink ID="HLBACK" runat="server" NavigateUrl="~/CustEventReport.aspx" ForeColor="#0066FF" Visible="false">חזרה</asp:HyperLink>
                  <br />
                   <asp:Button runat="server" Text="מחיקה" Width="80px" ID="BTNCNCL" Visible="false"
                      onclientclick="return confirm('האם למחוק את הטופס?');" BackColor="#FFCC66" 
                      CausesValidation="False"  />
              </td>
            </tr>
            <tr>
            <td colspan="2" valign="top">
                <asp:RangeValidator ID="RangeValidator1" runat="server" 
                    ControlToValidate="tbdate" Display="Dynamic" ErrorMessage="תאריך לא חוקי" 
                    MaximumValue="2015-12-31" MinimumValue="2000-1-1" Type="Date"></asp:RangeValidator>
               </td>
               <td>
                   &nbsp;</td>
            </tr>
            </table>
  </div>
  <table width="100%">
      <tr>
            <td width="100%">
                <asp:Label ID="lblgrouphdr" runat="server" font-size="Large" Font-Bold="True" 
					BackColor="Blue" ForeColor="Wheat" Width="100%" Visible="false" ></asp:Label>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="הפרק הראשון" Visible="false" />
            </td>
            <td>
                <asp:Button ID="Button2" runat="server" Text="הפרק הקודם" Visible="true" />
            </td>
            <td>
                <asp:Button ID="Button3" runat="server" Text="הפרק הבא" Visible="true" />
            </td>
            <td>
                <asp:Button ID="Button4" runat="server" Text="הפרק האחרון" Visible="false" />                            

            </td>
     </tr>
 </table>

  <asp:Panel runat="server" Width="100%" ScrollBars="Auto">
     <div runat="server" id="divlvq" style="vertical-align:top" width="100%">
        <asp:ListView ID="lv_q" runat="server">
            <LayoutTemplate>
                <table  cellpadding="4" border="2">
                    <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
                </table>
            </LayoutTemplate>
            <ItemTemplate>
                <tbody>
                    <tr>
                       <td style="background-color:Silver;width:3%"'<%# "background-color:Silver;width:3%;" & Eval("style") %>' >
                            <%#Eval("id")%>
                        </td>
                        <td style='<%# "background-color:Silver;width:37%;vertical-align:text-top;font-weight:bold;" & Eval("style") %>' >
                            <%#Eval("txt")%>
                        </td>
                        <td style='<%#Eval("style")%>' width="60%">
                            <asp:UpdatePanel runat="server" ID="up_q" UpdateMode="Always" >
                            <ContentTemplate>
                             <asp:HiddenField ID="HDNANS_q" Value='<%#Eval("ans") %>' runat="server" />
                            <asp:HiddenField runat="server" ID="hdnid_q" value='<%#Eval("id")%>' />
                            <asp:HiddenField runat="server" ID="HDNAID_q" Value='<%#Eval("ansID") %>' />
                            <asp:HiddenField runat="server" ID="HDNFRMID_q" Value='<%#Eval("FrameID") %>' />
                            <asp:TreeView DataSourceID="xFrames"  EnableClientScript="true" OnPreRender="TVFrames_PreRender" 
                                    runat="server" onTreeNodeCheckChanged="tvframes_TreeNodeCheckChanged" 
                                    ontreenodedatabound="tvframes_TreeNodeDataBound" ID="tvframes" Visible='<%#Eval("control")="treeview" %>'>
                                <DataBindings>
                                    <asp:TreeNodeBinding DataMember="frame" TextField="name" ValueField="CategoryID" />
                                </DataBindings>
                            </asp:TreeView>
                            <asp:RadioButtonList ID="rbla_q" onclick='thisrow(this)'  AutoPostBack="false" OnSelectedIndexChanged="rbla_SelectedIndexChanged" CausesValidation="true" OnPreRender="rbla_PreRender" CssClass="rbl" AppendDataBoundItems="true" runat="server" OnLoad="rbla_Load" RepeatDirection="Horizontal" DataTextField="txt" Font-Size="X-Small" RepeatLayout="Table" DataValueField="val" CellPadding="8" CellSpacing="6" >
                            </asp:RadioButtonList>
                             <asp:RangeValidator runat="server" ID="rvrbl" OnPreRender="rv_PreRender" ControlToValidate="rbla_q" SetFocusOnError="true" ErrorMessage="לא ניתן לשנות ערכים בטופס סגור" Display="Dynamic" Type="Integer" MaximumValue="-5" MinimumValue="-5" Enabled="false" />
		                    <asp:TextBox ID="TBDET_S" AutoPostBack="false"  OnTextChanged="tb_OnTextChanged" runat="server" TextMode="MultiLine" Rows="4" Width="450px" Visible='<%#Eval("tb") = "yes" %>' Text='<%#Eval("textdet") %>'></asp:TextBox>
		                    <asp:Button ID="btndtsave" runat="server" Text="שמירת הטקסט החופשי" Visible="false" /> 
                            </ContentTemplate>
                            </asp:UpdatePanel>
                        </td>
                    </tr>
                </tbody>
           </ItemTemplate>
       </asp:ListView>  
  </div>
<div runat="server" id="divlvp">
    <asp:ListView ID="lv_p" runat="server">
        <LayoutTemplate>
            <table width="100%">
                <asp:PlaceHolder ID="itemPlaceHolder" runat="server" />
            </table>
        </LayoutTemplate>
        <ItemTemplate>
            <tbody>
                <tr>
                    <td style='<%#Eval("style") %>'>
                        <asp:Label ID="lbltxt" runat="server" Text='<%#Eval("txt")%>' Width="100%" ></asp:Label>
                    </td>
                </tr>
            </tbody>
        </ItemTemplate>
    </asp:ListView>  
</div>
   
  </asp:Panel>
  <div>
    <table width="100%">
        <tr>
            <td width="100%" />
            <td>
                <asp:Button ID="Button1A" runat="server" Text="הפרק הראשון" Visible="false" />
            </td>
            <td>
                <asp:Button ID="Button2A" runat="server" Text="הפרק הקודם" Visible="true" />
            </td>
            <td>
                <asp:Button ID="Button3A" runat="server" Text="הפרק הבא" Visible="true" />
            </td>
            <td>
                <asp:Button ID="Button4A" runat="server" Text="הפרק האחרון" Visible="false" />
            </td>
            <td>
               <asp:Button runat="server" Text="שליחה למערכת"  ID="btncls0" Height="50"  
                    Font-Bold="true" Font-Size="Medium" ForeColor="Wheat" BackColor="#3399FF"
                      onclick="BTNCLS_Click" />
            </td>
        </tr>
    </table>
  </div>
</asp:Content>

